export const Constants = {
  /** Estatus de registros */
  STATUS_PENDING: 1,
  STATUS_ACCEPT: 2,
  STATUS_FINISH: 3,
  STATUS_CANCEL: 4,

  /** Roles */
  ROLE_SYSTEM_MANAGER: 1,
  ROLE_TRUST: 2,
  ROLE_TECHNICAL: 3,
  ROLE_SYSTEM_ASSISTANT: 4,
  ROLE_AREA_RESPONSIBLE: 5,
  ROLE_COORDINATOR: 6,
  ROLE_ASSISTANT: 7,
  ROLE_TECH_SERVICES_HEAD: 8,
  ROLE_LABORATORY_AUXILIAR: 9,
}
