import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import User from 'App/Models/User'
import { Constants as cnst } from  '../../constants'

export default class UserSeeder extends BaseSeeder {
  public async run () {
    await User.createMany([
      {
        name: 'Admin',
        lastName: 'Admin',
        roleId: cnst.ROLE_SYSTEM_MANAGER,
        careerId: 1,
        shiftId: 3,
        email: 'admin@ut.com',
        password: 'password',
        isAdmin: 1,
        isActive: 1,
      },
      {
        name: 'Confianza',
        lastName: 'Confianza',
        roleId: cnst.ROLE_TRUST,
        careerId: 1,
        shiftId: 3,
        email: 'confianza@ut.com',
        password: 'password',
        isAdmin: 0,
        isActive: 1,
      },
      {
        name: 'Tecnico',
        lastName: 'Tecnico',
        roleId: cnst.ROLE_TECHNICAL,
        careerId: 1,
        shiftId: 3,
        email: 'tecnico@ut.com',
        password: 'password',
        isAdmin: 0,
        isActive: 1,
      },
      {
        name: 'Asistente',
        lastName: 'de Sistemas',
        roleId: cnst.ROLE_SYSTEM_ASSISTANT,
        careerId: 1,
        shiftId: 3,
        email: 'asistente_sistemas@ut.com',
        password: 'password',
        isAdmin: 0,
        isActive: 1,
      },
      {
        name: 'Responsable',
        lastName: 'De Area',
        roleId: cnst.ROLE_AREA_RESPONSIBLE,
        careerId: 1,
        shiftId: 3,
        email: 'responsable_area@ut.com',
        password: 'password',
        isAdmin: 0,
        isActive: 1,
      },
      {
        name: 'Coordinador',
        lastName: 'Coordinador',
        roleId: cnst.ROLE_COORDINATOR,
        careerId: 1,
        shiftId: 3,
        email: 'coordinador@ut.com',
        password: 'password',
        isAdmin: 0,
        isActive: 1,
      },
      {
        name: 'Asistente',
        lastName: 'Asistente',
        roleId: cnst.ROLE_ASSISTANT,
        careerId: 1,
        shiftId: 3,
        email: 'asistente@ut.com',
        password: 'password',
        isAdmin: 0,
        isActive: 1,
      },
      {
        name: 'Jefe',
        lastName: 'Servicios Tec',
        roleId: cnst.ROLE_TECH_SERVICES_HEAD,
        careerId: 1,
        shiftId: 3,
        email: 'jefeservtec@ut.com',
        password: 'password',
        isAdmin: 0,
        isActive: 1,
      },
      {
        name: 'Auxiliar',
        lastName: 'Laboratorio',
        roleId: cnst.ROLE_LABORATORY_AUXILIAR,
        careerId: 1,
        shiftId: 3,
        email: 'auxiliarlab@ut.com',
        password: 'password',
        isAdmin: 0,
        isActive: 1,
      },
    ])
  }
}
