import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import User from 'App/Models/User'

export default class UserSeeder extends BaseSeeder {
  public async run () {
    await User.createMany([
      {
        name: 'Admin',
        lastName: 'Admin',
        roleId: 1,
        careerId: 1,
        shiftId: 3,
        email: 'admin@ut.com',
        password: 'pssword',
        isAdmin: 1,
        isActive: 1,
      },
      {
        name: 'Confianza',
        lastName: 'Confianza',
        roleId: 2,
        careerId: 1,
        shiftId: 3,
        email: 'confianza@gmail.com',
        password: 'password',
        isAdmin: 0,
        isActive: 0,
      },
      {
        name: 'Tecnico',
        lastName: 'Tecnico',
        roleId: 3,
        careerId: 1,
        shiftId: 3,
        email: 'tecnico@gmail.com',
        password: 'password',
        isAdmin: 0,
        isActive: 0,
      },
      {
        name: 'AsistenteSistemas',
        lastName: 'AsistenteSistmas',
        roleId: 4,
        careerId: 1,
        shiftId: 3,
        email: 'asistente_sistemas@gmail.com',
        password: 'password',
        isAdmin: 0,
        isActive: 0,
      },
      {
        name: 'ResponsableArea',
        lastName: 'ResponsableArea',
        roleId: 5,
        careerId: 1,
        shiftId: 3,
        email: 'responsable_area@gmail.com',
        password: 'password',
        isAdmin: 0,
        isActive: 0,
      },
      {
        name: 'Coordinador',
        lastName: 'Coordinador',
        roleId: 6,
        careerId: 1,
        shiftId: 3,
        email: 'coordinador@gmail.com',
        password: 'password',
        isAdmin: 0,
        isActive: 0,
      },
      {
        name: 'Asistente',
        lastName: 'Asistente',
        roleId: 7,
        careerId: 1,
        shiftId: 3,
        email: 'asistente@gmail.com',
        password: 'password',
        isAdmin: 0,
        isActive: 0,
      },
    ])
  }
}
